### PR TITLE
cmake: refactor to work with CPM.cmake

### PR DESCRIPTION
**Pull request by bd4**
Moved clir to top level project directory and moved all related files (include, cmake) so it can work as a self contained project and use correct relative cmake paths. This makes it so the entire project will work correctly as a subdirectory of another project, which is how CPM.cmake does things. Also changed many cmake variables to use CURRENT or PROJECT variants of source / binary dir.

### CODE REVIEW

**Comment by bd4** [comment]
Example usage:
```
      CPMAddPackage(
        NAME bbfft
        #GITHUB_REPOSITORY intel/double-batched-fft-library
        #GIT_TAG main
        GITHUB_REPOSITORY bd4/double-batched-fft-library
        GIT_TAG pr/cpm
        OPTIONS
          "BUILD_SYCL ON"
          "BUILD_TESTING OFF"
          "SYCL_COMPILE_OPTIONS -fsycl"
          "SYCL_LINK_OPTIONS -fsycl"
        FIND_PACKAGE_ARGUMENTS "CONFIG"
      )
```
See also https://github.com/wdmapp/gtensor/pull/245

**Review by uphoffc — CHANGES_REQUESTED** [review]
Hi Bryce,
thanks for the contribution, looks good to me.

Could you make the following small changes:
1) Could you move the cpp files from clir to clir/src?
2) Could you sign your commits as explained in the [contributers guide](https://github.com/intel/double-batched-fft-library/blob/main/CONTRIBUTING.md)?

Best regards,
Carsten

**Comment by bd4** [comment]
Thanks, I moved the clir source to clir/src, had to create a new intermediate CMakeLists.txt add I copied the license to the new file, and added the sign off.

I tested by building the gtensor bbfft branch and running test_fft, using `find_package` after doing cmake -t install in bbfft and setting CMAKE_PREFIX_PATH, and then again by using CPMAddPackage pointing at the bbfft branch in the PR. Both are working. Heavy cmake refactors always make me nervous though, is there anything else I should test?

**Comment by uphoffc** [comment]
I downloaded, built and installed your branch, too, and it works fine on my system, so I think we can merge now.
About the license: Do you want / need to add your affiliation to the LICENSE.md file? E.g.
Copyright (c) 2023, University of Chicago
below the Intel Corporation line.

**Comment by bd4** [comment]
> Do you want / need to add your affiliation to the LICENSE.md file? E.g. Copyright (c) 2023, University of Chicago below the Intel Corporation line.

Asking around to figure this out, I think is a nice thing to do but not actually aware if there are specific rules around it

**Comment by bd4** [comment]
Talked it over with some folks on the Argonne slack, given my funding, adding UChicago Argonne LLC to the copyright seems most appropriate, did I add it correctly? Thanks!

**Comment by uphoffc** [comment]
Yes that looks fine. Thanks for the contribution!

**Pull request merged**
